version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/emails"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
