version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.sun.mail:jakarta.mail
    versions:
    - ">= 2.0.0"
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sass  # deprecated `/` for division
    versions:
    - ">= 1.33.0"
  - dependency-name: vue
    versions:
    - ">= 3.0.0"
  - dependency-name: "@vue/test-utils"
    versions:
    - ">= 2.0.0"
- package-ecosystem: npm
  directory: "/emails"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "America/Los_Angeles"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
