version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.sun.mail:jakarta.mail
    versions:
    - ">= 2.0.0"
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mock-apollo-client
    versions:
    - ">= 1.0.0"
