version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx2048m

    steps:
      # get code
      - checkout
      # handle dependency caching and run build
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ .Revision }}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-
      - run:
          name: Set Maven Version
          command: |
            BASE_VERSION=$(mvn -q  -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec|sed 's/-SNAPSHOT.*//')
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              NEW_PROJECT_VERSION=${BASE_VERSION}.${CIRCLE_BUILD_NUM}
            else
              NEW_PROJECT_VERSION=${BASE_VERSION}-${CIRCLE_BRANCH}-SNAPSHOT
            fi
            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${NEW_PROJECT_VERSION}
      - run: mvn install -U
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ .Revision }}
      # collect test results and upload coverage
      - run: mkdir -p ~/test_results
      - run: find . -type f -regex ".*/target/surefire-reports/junitreports/.*xml" -exec cp {} ~/test_results/ \;
      - store_test_results:
          path: ~/test_results
      - store_artifacts:
          path: ~/test_results
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      # collect docs
      - run: mkdir -p ~/docs
      - run: find . -type d -name 'dokka' -exec cp -r {} ~/docs/ \;
      - store_artifacts:
          path: ~/docs
      # collect built packages and save to workspace for deploy
      - run: mkdir -p ~/jars
      - run: find . -type f -regex ".*/target/.*jar" -exec cp {} ~/jars/ \;
      - run: find . -type f -regex ".*/target/.*zip" -exec cp {} ~/jars/ \;
      - run:
          name: Notify of Pending Deployment
          command: |
            CURRENT_VERSION=$(mvn -q  -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
            git fetch --tags
            PREVIOUS_VERSION=$(git tag | sort -V | tail -n 1)
            git log --pretty=format:'* %s\r\n' ${PREVIOUS_VERSION}..HEAD | sed 's/"/\\"/g'|tr -d '\n' > ~/jars/release-notes.txt
            RELEASE_NOTES=$(cat ~/jars/release-notes.txt)
            if [ "${CIRCLE_BRANCH}" = "master" -a "${SLACK_NOTIFICATION_WEBHOOK}" != "" ]; then
              WORKFLOW_URL="https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}"
              curl -X POST -d "payload={\"attachments\":[{ \"mrkdwn_in\":[\"text\"], \"color\":\"#439FE0\", \"fallback\":\"Deploy Ready Notification\", \"pretext\":\"Deploy Ready Notification\", \"text\":\"*Project* \`${CIRCLE_PROJECT_REPONAME}\`\n*Branch* \`${CIRCLE_BRANCH}\`\n*Version* \`${CURRENT_VERSION}\`\nClick <$WORKFLOW_URL|here> to approve the deploy\nRelease Notes:\n\`\`\`\n${RELEASE_NOTES}\n\`\`\`\"}]}" ${SLACK_NOTIFICATION_WEBHOOK}
            fi
      - store_artifacts:
          path: ~/jars
      - persist_to_workspace:
          root: ~/jars
          paths:
            - .

  deploy:
    docker:
      - image: circleci/python:3.6 # more likely to already be on the new host than the java image
    steps:
      - attach_workspace:
          at: ~/jars
      - run: sudo apt install awscli
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            CURRENT_VERSION=$(ls ~/jars/server-*-elasticbeanstalk.zip | sed 's/^.*jars\/server-\(.*\)-elasticbeanstalk\.zip$/\1/')
            aws s3 cp `ls ~/jars/server-*-elasticbeanstalk.zip` s3://elasticbeanstalk-${AWS_DEFAULT_REGION}-${AWS_ACCOUNT_ID}/${CIRCLE_PROJECT_REPONAME}-${CURRENT_VERSION}.zip
            aws elasticbeanstalk create-application-version --application-name ${CIRCLE_PROJECT_REPONAME} --version-label ${CURRENT_VERSION}  --source-bundle S3Bucket=elasticbeanstalk-${AWS_DEFAULT_REGION}-${AWS_ACCOUNT_ID},S3Key=${CIRCLE_PROJECT_REPONAME}-${CURRENT_VERSION}.zip
            aws elasticbeanstalk update-environment --application-name ${CIRCLE_PROJECT_REPONAME} --environment-name "${CIRCLE_PROJECT_REPONAME}-prod" --version-label ${CURRENT_VERSION}
      - run:
          name: Create Release Notes
          command: |
            CURRENT_VERSION=$(ls ~/jars/server-*-elasticbeanstalk.zip | sed 's/^.*jars\/server-\(.*\)-elasticbeanstalk\.zip$/\1/')
            RELEASE_NOTES=$(cat ~/jars/release-notes.txt)
            if [ "${GITHUB_AUTH_TOKEN}" != "" -a "${RELEASE_NOTES}" != "" ]; then
              curl -H "Authorization: bearer ${GITHUB_AUTH_TOKEN}" -X POST "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases" -X POST -d "{\"tag_name\":\"${CURRENT_VERSION}\", \"name\":\"${CURRENT_VERSION}\", \"target_commitish\":\"${CIRCLE_SHA1}\", \"body\": \"${RELEASE_NOTES}\"}"
            fi

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
