mutation AddUser($name: String!, $email: String!, $instanceId: UUID!) {
  user(
    user: {
      name: $name
      email: $email
      instanceId: $instanceId
      timeZoneId: "Autodetect"
      admin: false
      notifyViaEmail: false
    }
  ) {
    id
    instanceId
    email
    name
    admin
    timeZoneId
  }
}
