query CompletedQuestions {
  closedQuestions {
    activeAt
    answer
    author {
      id
      name
    }
    authorId
    body
    closedAt
    id
    response {
      grade {
        bonus
        correct
        id
        score
      }
      id
      response
      ruleReferences
      user {
        id
        name
      }
    }
    ruleReferences
  }
}
