query CompletedQuestions {
    closedQuestions {
        id,
        authorId,
        body,
        activeAt,
        closedAt,
        answer,
        ruleReferences,
        response {
            id
            response,
            ruleReferences,
            grade {
                id,
                correct,
                bonus,
                score
            }
        }
    }
}