query CompletedQuestions($startTime: DateTime, $endTime: DateTime) {
  closedQuestions(startTime: $startTime, endTime: $endTime) {
    activeAt
    answer
    author {
      id
      name
    }
    authorId
    body
    closedAt
    id
    type
    imageUrl
    answerChoices {
      id
      letter
      answer
    }

    response {
      grade {
        bonus
        correct
        id
        score
      }
      id
      response
      ruleReferences
      user {
        id
        name
      }
    }
    ruleReferences
    percentCorrect
  }
}
