query currentQuestions {
    activeQuestions {
        id,
        authorId,
        author {
            id
            name
        }
        body,
        activeAt,
        closedAt,
        response {
            id,
            response,
            ruleReferences
        }
    }
}