query CurrentQuestions {
  activeQuestions {
    activeAt
    author {
      id
      name
    }
    authorId
    body
    closedAt
    id
    response {
      id
      response
      ruleReferences
    }
  }
}
