query CurrentUser($endTime: DateTime) {
  user {
    admin
    email
    id
    instance {
      id
      name
      defaultQuestionType
      seasons(endTime: $endTime) {
        id
        name
        startTime
        endTime
      }
    }
    instanceId
    name
    notifyViaEmail
    timeZoneId
  }
}
