query Grader($includeGraded: Boolean!) {
  responses(includeGraded: $includeGraded) {
    grade {
      bonus
      correct
      id
      score
    }
    id
    question {
      activeAt
      answer
      author {
        id
        name
      }
      body
      id
      ruleReferences
    }
    response
    ruleReferences
    user {
      email
      id
      name
    }
  }
}
