mutation submitGrade($id: UUID, $responseId: UUID!, $bonus: Int, $correct: Boolean) {
    grade(grade: {
        bonus: $bonus
        correct: $correct
        id: $id
        responseId: $responseId
    }) {
        id
    }
}