query Grader(
  $includeGraded: Boolean!
  $startTime: DateTime
  $endTime: DateTime
) {
  responses(
    includeGraded: $includeGraded
    startTime: $startTime
    endTime: $endTime
  ) {
    grade {
      bonus
      correct
      id
      score
    }
    id
    question {
      activeAt
      answer
      author {
        id
        name
      }
      body
      id
      ruleReferences
      type
      imageUrl
      answerChoices {
        id
        letter
        answer
      }
    }
    response
    ruleReferences
    user {
      email
      id
      name
    }
  }
}
