mutation SaveQuestion(
  $activeAt: DateTime!
  $answer: String!
  $authorId: UUID!
  $body: String!
  $closedAt: DateTime!
  $id: UUID
  $ruleReferences: String!
  $type: QuestionType!
  $answerChoices: [AnswerChoiceInput!]
) {
  question(
    question: {
      activeAt: $activeAt
      answer: $answer
      authorId: $authorId
      body: $body
      closedAt: $closedAt
      id: $id
      ruleReferences: $ruleReferences
      type: $type
      answerChoices: $answerChoices
    }
  ) {
    id
  }
}
