mutation SaveResponse(
  $id: UUID
  $questionId: UUID!
  $response: String!
  $ruleReferences: String!
  $userId: UUID!
) {
  response(
    response: {
      id: $id
      questionId: $questionId
      response: $response
      ruleReferences: $ruleReferences
      userId: $userId
    }
  ) {
    id
    response
    ruleReferences
    user {
      id
      name
    }
    grade {
      id
      correct
    }
    question {
      activeAt
      answer
      author {
        id
        name
      }
      authorId
      body
      closedAt
      id
      type
      imageUrl
      answerChoices {
        id
        letter
        answer
      }
      ruleReferences
    }
  }
}
