mutation updateUser(
    $name: String!,
    $id: UUID!,
    $instanceId: UUID!,
    $email: String!,
    $admin: Boolean!,
    $timeZoneId: String!,
    $notifyViaEmail: Boolean!
) {
    user(user: {
        id: $id
        instanceId: $instanceId
        email: $email
        name: $name
        admin: $admin
        timeZoneId: $timeZoneId
        notifyViaEmail: $notifyViaEmail
    }) {
      id
      instanceId
      email
      name
      admin
      timeZoneId
    }
}